name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    env:
      TEST: 1

    steps:
      - uses: actions/checkout@v2

      - name: Create GoogleService-Info.plist from GOOGLE_SERVICE_INFO_PLIST
        run: |
          echo secrets.GOOGLE_SERVICE_INFO_PLIST | base64 -d >> Tests/GoogleService-Info.plist

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test